FROM node:22-alpine as build-stage

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM node:22-alpine as production-stage

WORKDIR /app

COPY --from=build-stage /app/dist /app 

COPY --from=build-stage /app/package.json /app/package.json

WORKDIR /app

RUN npm install --only=production

EXPOSE 3000

CMD ["node", "/app/main.js"]
